name: Check MDN Outdated Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  check-outdated:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout translated-content
        uses: actions/checkout@v4
        with:
          repository: 'mdn/translated-content'
          path: 'translated-content'

      - name: Checkout content
        uses: actions/checkout@v4
        with:
          repository: 'mdn/content'
          path: 'content'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install GitPython markdownify

      - name: Generate outdated report
        run: python generate_diff.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: outdated-diff-report
          path: output/