name: Check Outdated Translations

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天執行一次

jobs:
  check_outdated:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout finddiff (this repo)
        uses: actions/checkout@v4
        with:
          path: finddiff

      - name: Checkout mdn/translated-content
        uses: actions/checkout@v4
        with:
          repository: mdn/translated-content
          path: translated-content
          fetch-depth: 0

      - name: Checkout mdn/content
        uses: actions/checkout@v4
        with:
          repository: mdn/content
          path: content
          fetch-depth: 0

      - name: Install dependencies
        run: pip install ansi2html

      - name: Check outdated translations
        run: bash finddiff/scripts/check_outdated.sh

      - name: Commit and push updates
        run: |
          cd finddiff
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add outdate_report
          git commit -m "Update outdated translation report" || exit 0
          git push