name: Check Outdated Translations

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天執行
  workflow_dispatch:

jobs:
  check-outdated:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (for scripts and pages)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout translated-content
        uses: actions/checkout@v4
        with:
          repository: 'mdn/translated-content'
          path: 'translated-content'
          fetch-depth: 0

      - name: Checkout content
        uses: actions/checkout@v4
        with:
          repository: 'mdn/content'
          path: 'content'
          fetch-depth: 0

      - name: Debug file structure
        run: ls -R
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install GitPython markdown2

      - name: Run outdated check script
        run: cd $GITHUB_WORKSPACE && python scripts/check_outdated.py

      - name: Upload diff data
        uses: actions/upload-artifact@v4
        with:
          name: outdated-diff
          path: outdated_diff.json

  deploy-gh-pages:
    needs: check-outdated
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download diff data
        uses: actions/download-artifact@v4
        with:
          name: outdated-diff
          path: data

      - name: Generate outdated page
        run: cd $GITHUB_WORKSPACE && python scripts/generate_page.py

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public